//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from calc.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class CalculadoraLexer : Lexer {
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, INT=5, WS=6;
	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "INT", "WS"
	};


	public CalculadoraLexer(ICharStream input)
		: base(input)
	{
		Interpreter = new LexerATNSimulator(this,_ATN);
	}

	private static readonly string[] _LiteralNames = {
		null, "'+'", "'-'", "'*'", "'/'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "INT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "calc.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	private static string _serializedATN = _serializeATN();
	private static string _serializeATN()
	{
	    StringBuilder sb = new StringBuilder();
	    sb.Append("\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x2\b#");
		sb.Append("\b\x1\x4\x2\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6");
		sb.Append("\x4\a\t\a\x3\x2\x3\x2\x3\x3\x3\x3\x3\x4\x3\x4\x3\x5\x3\x5\x3");
		sb.Append("\x6\x6\x6\x19\n\x6\r\x6\xE\x6\x1A\x3\a\x6\a\x1E\n\a\r\a\xE\a");
		sb.Append("\x1F\x3\a\x3\a\x2\x2\b\x3\x3\x5\x4\a\x5\t\x6\v\a\r\b\x3\x2\x4");
		sb.Append("\x3\x2\x32;\x5\x2\v\f\xF\xF\"\"$\x2\x3\x3\x2\x2\x2\x2\x5\x3");
		sb.Append("\x2\x2\x2\x2\a\x3\x2\x2\x2\x2\t\x3\x2\x2\x2\x2\v\x3\x2\x2\x2");
		sb.Append("\x2\r\x3\x2\x2\x2\x3\xF\x3\x2\x2\x2\x5\x11\x3\x2\x2\x2\a\x13");
		sb.Append("\x3\x2\x2\x2\t\x15\x3\x2\x2\x2\v\x18\x3\x2\x2\x2\r\x1D\x3\x2");
		sb.Append("\x2\x2\xF\x10\a-\x2\x2\x10\x4\x3\x2\x2\x2\x11\x12\a/\x2\x2\x12");
		sb.Append("\x6\x3\x2\x2\x2\x13\x14\a,\x2\x2\x14\b\x3\x2\x2\x2\x15\x16\a");
		sb.Append("\x31\x2\x2\x16\n\x3\x2\x2\x2\x17\x19\t\x2\x2\x2\x18\x17\x3\x2");
		sb.Append("\x2\x2\x19\x1A\x3\x2\x2\x2\x1A\x18\x3\x2\x2\x2\x1A\x1B\x3\x2");
		sb.Append("\x2\x2\x1B\f\x3\x2\x2\x2\x1C\x1E\t\x3\x2\x2\x1D\x1C\x3\x2\x2");
		sb.Append("\x2\x1E\x1F\x3\x2\x2\x2\x1F\x1D\x3\x2\x2\x2\x1F \x3\x2\x2\x2");
		sb.Append(" !\x3\x2\x2\x2!\"\b\a\x2\x2\"\xE\x3\x2\x2\x2\x5\x2\x1A\x1F\x3");
		sb.Append("\b\x2\x2");
	    return sb.ToString();
	}

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
