//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Line.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class LinhaLexer : Lexer {
	public const int
		T__0=1, NOME_LINHA=2, STRING=3, WS=4;
	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "NOME_LINHA", "STRING", "WS"
	};


	public LinhaLexer(ICharStream input)
		: base(input)
	{
		Interpreter = new LexerATNSimulator(this,_ATN);
	}

	private static readonly string[] _LiteralNames = {
		null, "':'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "NOME_LINHA", "STRING", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Line.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	private static string _serializedATN = _serializeATN();
	private static string _serializeATN()
	{
	    StringBuilder sb = new StringBuilder();
	    sb.Append("\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x2\x6");
		sb.Append("\"\b\x1\x4\x2\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x3\x2\x3");
		sb.Append("\x2\x3\x3\x6\x3\xF\n\x3\r\x3\xE\x3\x10\x3\x4\x3\x4\a\x4\x15");
		sb.Append("\n\x4\f\x4\xE\x4\x18\v\x4\x3\x4\x3\x4\x3\x5\x6\x5\x1D\n\x5\r");
		sb.Append("\x5\xE\x5\x1E\x3\x5\x3\x5\x3\x16\x2\x6\x3\x3\x5\x4\a\x5\t\x6");
		sb.Append("\x3\x2\x4\x4\x2\x43\\\x63|\x5\x2\v\f\xF\xF\"\"$\x2\x3\x3\x2");
		sb.Append("\x2\x2\x2\x5\x3\x2\x2\x2\x2\a\x3\x2\x2\x2\x2\t\x3\x2\x2\x2\x3");
		sb.Append("\v\x3\x2\x2\x2\x5\xE\x3\x2\x2\x2\a\x12\x3\x2\x2\x2\t\x1C\x3");
		sb.Append("\x2\x2\x2\v\f\a<\x2\x2\f\x4\x3\x2\x2\x2\r\xF\t\x2\x2\x2\xE\r");
		sb.Append("\x3\x2\x2\x2\xF\x10\x3\x2\x2\x2\x10\xE\x3\x2\x2\x2\x10\x11\x3");
		sb.Append("\x2\x2\x2\x11\x6\x3\x2\x2\x2\x12\x16\a$\x2\x2\x13\x15\v\x2\x2");
		sb.Append("\x2\x14\x13\x3\x2\x2\x2\x15\x18\x3\x2\x2\x2\x16\x17\x3\x2\x2");
		sb.Append("\x2\x16\x14\x3\x2\x2\x2\x17\x19\x3\x2\x2\x2\x18\x16\x3\x2\x2");
		sb.Append("\x2\x19\x1A\a$\x2\x2\x1A\b\x3\x2\x2\x2\x1B\x1D\t\x3\x2\x2\x1C");
		sb.Append("\x1B\x3\x2\x2\x2\x1D\x1E\x3\x2\x2\x2\x1E\x1C\x3\x2\x2\x2\x1E");
		sb.Append("\x1F\x3\x2\x2\x2\x1F \x3\x2\x2\x2 !\b\x5\x2\x2!\n\x3\x2\x2\x2");
		sb.Append("\x6\x2\x10\x16\x1E\x3\b\x2\x2");
	    return sb.ToString();
	}

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
